version: 1.2
workflows:
    - name: vcf_to_plink2
      subclass: WDL
      primaryDescriptorPath: /vcf_to_plink2.wdl
      testParameterFiles:
          - /vcf_to_plink2.json
    - name: make_fbm
      subclass: WDL
      primaryDescriptorPath: /make_fbm.wdl
      testParameterFiles:
          - /make_fbm.json
    - name: convert_lanc
      subclass: WDL
      primaryDescriptorPath: /convert_lanc.wdl
      testParameterFiles:
          - /convert_lanc.json
    - name: fit_haudi
      subclass: WDL
      primaryDescriptorPath: /fit_haudi.wdl
      testParameterFiles:
          - /fit_haudi.json
    - name: score_pgs
      subclass: WDL
      primaryDescriptorPath: /score_pgs.wdl
      testParameterFiles:
          - /score_pgs.json
